name: Gamet
description: Create awesome games!
author: Olyno
version: 2.0.4
main: com.olyno.gamet.Gamet
softdepend: [Skript]
commands:
  game:
    description: Create awesome games with this command!
    usage: §c[Gamet] Make /game help to show help message
    permission: game.use_command
    permission-message: §cYou don't have the permission to use this command
  team:
    description: Create awesome teams for your games with this command!
    usage: §c[Gamet] Make /game help to show help message
    permission: team.use_command
    permission-message: §cYou don't have the permission to use this command
