name: Gamet
description: Create awesome games!
author: Olyno
version: 3.0.0
main: com.olyno.gamet.Gamet
softdepend: [Skript]
commands:
  gamet:
    description: Show awesome gamet commands
    usage: "§c[Gamet] Make \"/gamet\" help to show help message"
    permission: gamet.use_command
    permission-message: §cYou don't have the permission to use this command
  game:
    description: Create awesome games with this command!
    usage: "§c[Gamet] Make \"/gamet\" help to show help message"
    permission: game.use_command
    permission-message: §cYou don't have the permission to use this command
  team:
    description: Create awesome teams for your games with this command!
    usage: "§c[Gamet] Make \"/gamet\" help to show help message"
    permission: team.use_command
    permission-message: §cYou don't have the permission to use this command
